/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { JSX } from "react";

export function AbelBust(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("https://fjvfwbnbufwhevhivldg.supabase.co/storage/v1/object/public/abelhii/abel-bust.glb");

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials["Material.002"]}
        position={[0, 1.311, -0.005]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials["Hair.001"]}
        position={[0.267, 1.677, 0.757]}
        rotation={[1.585, -0.057, 0.018]}
        scale={[1.193, 1.222, 1.437]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Hair.geometry}
        material={materials["Hair.001"]}
        position={[0, 1.472, -0.049]}
        scale={[0.838, 0.778, 0.778]}
      />
      <group
        position={[0.252, 1.457, 0.685]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={-0.112}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere002.geometry}
          material={materials["Eyeball.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere002_1.geometry}
          material={materials.pupil}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Glasses.geometry}
        material={materials["Material.005"]}
        position={[0.334, 1.479, 0.83]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.169}
      />
    </group>
  );
}

useGLTF.preload("/abel-bust.glb");
