/* eslint-disable @typescript-eslint/no-explicit-any */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { ComponentPropsWithRef } from "react";

export function AbelBust(props: ComponentPropsWithRef<"group">) {
  const { nodes, materials } = useGLTF(
    "https://fjvfwbnbufwhevhivldg.supabase.co/storage/v1/object/public/abelhii/abel-bust.glb"
  ) as any;

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials["Material.002"]}
        position={[0, 0, 0]}
      />

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials["Hair.001"]}
        position={[0.267, 0.366, 0.762]}
        rotation={[1.585, -0.057, 0.018]}
        scale={[1.193, 1.222, 1.437]}
      />

      <group
        position={[0.252, 0.146, 0.69]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={-0.112}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere002.geometry}
          material={materials["Eyeball.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere002_1.geometry}
          material={materials.pupil}
        />
      </group>

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Glasses.geometry}
        material={materials["Material.005"]}
        position={[0.334, 0.168, 0.835]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.169}
      />

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Hair2.geometry}
        material={materials["Hair.001"]}
        position={[0, 0.185, -0.193]}
        scale={[0.922, 0.751, 0.884]}
      />
    </group>
  );
}

useGLTF.preload(
  "https://fjvfwbnbufwhevhivldg.supabase.co/storage/v1/object/public/abelhii/abel-bust.glb"
);
